//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int IdAppointments { get; set; }
        public int IdUsersC { get; set; }
        public int IdUsersM { get; set; }
        public int IdServiceTypes { get; set; }
        public System.DateTime AppointmentDateTime { get; set; }
        public string Status { get; set; }
        public string PaymentMethod { get; set; }
        public string Comment { get; set; }
        public double FinalPrice { get; set; }
    
        public virtual ServiceTypes ServiceTypes { get; set; }
        public virtual ServiceTypes ServiceTypes1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
