//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenerFilm
    {
        public int GenerID { get; set; }
        public int FilmID { get; set; }
        public int ID { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
