//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterServices
    {
        public int IdMasterServices { get; set; }
        public int IdUsers { get; set; }
        public int IdServiceTypes { get; set; }
    
        public virtual ServiceTypes ServiceTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
